#!/usr/bin/env python

import re
import yaml
import os
import sys
import subprocess
from shlex import join
from datetime import datetime

def load_configuration():
  #print("Loading configuration...")
  config = None
  configFile = os.path.dirname(os.path.realpath(__file__))+"/ffmpeg-transcode.yaml"
  if not os.path.isfile(configFile):
    # Download default config file via wget
    subprocess.run(["wget", "-q", "https://github.com/ForsakenNGS/raspi-plex-transcode/raw/main/ffmpeg-transcode-example.yaml", "-O", configFile]);
  # Open and parse configuration file
  with open(configFile, "r") as stream:
    try:
      config = yaml.safe_load(stream)
    except yaml.YAMLError as e:
      print("Error loading config: "+configFile)
      print(e)
  return config

def parse_argument_value(value):
  if value is None:
    return None
  else:
    return " ".join(value)

def parse_arguments():
  #print("Parsing commandline arguments...")
  arguments = {
    "input": {},
    "output": {}
  }
  argSection = "input"
  argName = None
  argValue = None
  for arg in sys.argv[1:]:
    if arg.startswith("-"):
      if argName is not None:
        arguments[argSection][argName] = parse_argument_value(argValue)
        if argName == "-i":
          argSection = "output"
      argName = arg
      argValue = None
    else:
      if argValue is None:
        argValue = []
      argValue.append(arg)
  if argName is not None:
    arguments[argSection][argName] = parse_argument_value(argValue)
  return arguments

def profile_add(profilesByGroup, profile, profileGroup, priority):
  profilesByGroup[profileGroup] = profile;
  profilesByGroup[profileGroup]["priority"] = priority;
  return profilesByGroup

def profile_condition_arg(condition, arguments, config, profilesByGroup):
  # Get target profile settings
  profileTargetName = condition["profile"]
  profileTarget = config["profiles"][profileTargetName]
  profileGroup = "general"
  if "group" in profileTarget:
    profileGroup = profileTarget["group"]
  # Get current profile
  currentProfile = None
  currentPriority = -1
  if profileGroup in profilesByGroup:
    currentProfile = profilesByGroup[profileGroup]
    if "priority" in currentProfile:
      currentPriority = currentProfile["priority"]
  # Check priority
  conditionPriority = 0
  if "priority" in condition:
    conditionPriority = condition["priority"]
  if conditionPriority <= currentPriority:
    return profilesByGroup
  # Get argument value
  if not condition["argName"] in arguments[condition["argSection"]]:
    if condition["type"] == "missing":
      # Matches if argument is missing
      return profile_add(profilesByGroup, profileTarget, profileGroup, conditionPriority)
    else:
      # Condition type requires argument to be present
      return profilesByGroup
  value = arguments[condition["argSection"]][condition["argName"]]
  # Check condition
  if condition["type"] == "present":
    # Matches as soon as the argument is present
    return profile_add(profilesByGroup, profileTarget, profileGroup, conditionPriority)
  elif condition["type"] == "exact":
    # Exact value match
    if condition["value"] == value:
      return profile_add(profilesByGroup, profileTarget, profileGroup, conditionPriority)
  elif condition["type"] == "regex":
    # Regular expression match
    regexFlags = 0
    if ("ignorecase" in condition) and condition["ignorecase"]:
      regexFlags += re.IGNORECASE
    regexPattern = re.compile(condition["value"], regexFlags)
    if regexPattern.match(value):
      return profile_add(profilesByGroup, profileTarget, profileGroup, conditionPriority)
  return profilesByGroup

def profile_select(config, arguments):
  #print("Evaluating target profile...")
  profilesByGroup = {}
  if not "profile_select" in config:
    return None
  # Apply default profile
  if "default" in config["profile_select"]:
    profileTarget = config["profiles"][ config["profile_select"]["default"] ]
    profileGroup = "general"
    if "group" in profileTarget:
      profileGroup = profileTarget["group"]
    profile_add(profilesByGroup, profileTarget, profileGroup, 0)
  # Process profile conditions
  if "by_argument" in config["profile_select"]:
    for condition in config["profile_select"]["by_argument"]:
      profilesByGroup = profile_condition_arg(condition, arguments, config, profilesByGroup)
  # List and sort all selected profiles
  profileList = []
  for profileGroup in profilesByGroup:
    profileList.append(profilesByGroup[profileGroup])
  def profileSort(profile):
    return profile["priority"]
  profileList.sort(key=profileSort)
  return profileList

def profile_parameters(profile):
  argumentRepl = {
    "input": {},
    "output": {}
  }
  for profile in profiles:
    # Apply profile overrides
    if profile["input"] is not None:
      for argName in profile["input"]:
        argumentRepl["input"][argName] = profile["input"][argName]
    if profile["output"] is not None:
      for argName in profile["output"]:
        argumentRepl["output"][argName] = profile["output"][argName]
  # Build parameter list
  parameters = []
  argSection = "input"
  argName = None
  for arg in sys.argv[1:]:
    # Apply replacement if present
    replacement = None
    if argName is not None:
      if argName in argumentRepl[argSection]:
        replacement = argumentRepl[argSection][argName]
        del argumentRepl[argSection][argName]
    if replacement is not None:
      if replacement == "**REMOVE**":
        del parameters[-1]
        argName = None
        if not arg.startswith("-"):
          continue
      elif not arg.startswith("-"):
        arg = replacement
    # Check for end of input/output arguments
    if (arg == "-i") or (arg == "-segment_header_filename"):
      # Add parameters that were not present in the inital call from plex
      for argNameNew in argumentRepl[argSection]:
        argValueNew = argumentRepl[argSection][argNameNew]
        if argValueNew == "**REMOVE**":
          continue
        if not argNameNew in sys.argv:
          parameters.append(argNameNew)
          if argValueNew is not None:
            parameters.append(argValueNew)
    # Append to parameter list
    parameters.append(arg)
    # Update state
    if arg.startswith("-"):
      argName = arg
    else:
      if argName == "-i":
        argSection = "output"
      argName = None
  return parameters


config = load_configuration()
if config is None:
  print("Failed to load configuration! Exiting.")
  sys.exit(1)
arguments = parse_arguments()
profiles = profile_select(config, arguments)
parameters = profile_parameters(profiles)
executable = config["executable"]
parameters.insert(0, executable)

if ("log" in config) and ("debug" in config):
  with open(config["log"], "a") as logfile:
    logfile.write("Starting transcode at "+datetime.now().strftime("%Y-%m-%d %H:%M:%S")+"\n")
    logfile.write("Commandline: "+join(parameters)+"\n\n\n")

# Start transcode process
result = subprocess.run(parameters)

# Log transcode fail
if result.returncode > 0:
  if "log" in config:
    with open(config["log"], "a") as logfile:
      logfile.write("Failed transcode at "+datetime.now().strftime("%Y-%m-%d %H:%M:%S")+"\n")
      logfile.write("Commandline: "+join(parameters)+"\n")
      logfile.write("Return code: "+str(result.returncode)+"\n\n\n")

sys.exit(result.returncode)
